(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa-stable" "http://melpa.milkbox.net/packages/")
(source "melpa" "http://melpa.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
;(source "org" "http://orgmode.org/elpa/")

(depends-on "ack-and-a-half")
(depends-on "anything")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "fill-column-indicator")
(depends-on "flycheck")
(depends-on "helm-projectile")
(depends-on "ipython")
(depends-on "jedi")
(depends-on "magit")
(depends-on "neotree")
(depends-on "pallet")
(depends-on "perl-completion")
(depends-on "projectile")
(depends-on "python-mode")
(depends-on "solarized-theme")
(depends-on "undo-tree")
