(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "ack-and-a-half")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "flycheck")
(depends-on "jedi")
(depends-on "solarized-theme")
(depends-on "pallet")
(depends-on "undo-tree")
